spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/MyExampleDB?createDatabaseIfNotExist=true
    username: username
    password: password
    platform: mysql